import tensorflow as tf


MAX_CPUS = 64
DATA_TYPE = tf.float32
MATMUL_BATCHES_KW = 5
MATMUL_BATCHES_TD = 2
PREDICT_BATCHES = 2
TRAPDOOR_BATCHES = 4
CLUSTERING_BATCHES = 8

NUM_GPUS = 1

PROFILE_MATMUL = False

PROFILE_PREDICTION_REFINED = False
PROFILE_PREDICTION_K = False

PROFILE_STRATEGY = False
